# (c) 2008-2024 Sigasi
# License: BSD, see LICENSE for more details.

image: python:latest

workflow:
  rules:
    # Don't run while MR is "in draft"
    - if: $CI_MERGE_REQUEST_TITLE =~ /Draft:/
      when: never
    # Run tests on MRs and after merge into the main branch
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

unit-test:
  tags:
    - docker
  stage: test
  before_script:
    # Set up the test environment
    - python3 -m pip install -r requirements.txt
    - git config --global user.email "ci@sigasi.com"
    - git config --global user.name "Sigasi CI"
  script:
    - PYTHONPATH=$(pwd)/src:$(pwd)/src/SigasiProjectCreator/DotF python3 -m pytest --junitxml=test_report.xml --cov-report xml:coverage.xml --cov-report term --cov=src
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: test_report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  # Extract and report overall coverage from job output in MR
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
